# Generated by Django 4.0.6 on 2022-08-14 09:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('factories', '0003_alter_products_product_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='products',
            old_name='product_id',
            new_name='identity',
        ),
    ]
