# Generated by Django 4.0.6 on 2022-08-14 20:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('factories', '0004_rename_product_id_products_identity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='companies',
            name='identity',
        ),
        migrations.AlterField(
            model_name='companies',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='products',
            name='identity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relation', to='factories.companies'),
        ),
    ]
