# Generated by Django 4.0.6 on 2022-08-19 06:19

from django.db import migrations, models
import factories.models


class Migration(migrations.Migration):

    dependencies = [
        ('factories', '0005_remove_companies_identity_alter_companies_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='image',
            field=models.ImageField(null=True, upload_to=factories.models.upload_path),
        ),
    ]
